# Generated by Django 5.2.8 on 2025-11-26 21:18

import Orders.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(default=Orders.models.generate_random_code, primary_key=True, serialize=False)),
                ('total', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('returned', 'Returned'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('on_hold', 'On Hold'), ('partially_refunded', 'Partially Refunded'), ('partially_shipped', 'Partially Shipped')], default='pending')),
                ('delivery_address', models.CharField()),
                ('phone', models.CharField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Orders.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
    ]
