# Generated by Django 5.2.8 on 2025-11-17 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_alter_order_order_id_alter_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
