# Generated by Django 5.2.8 on 2025-11-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_remove_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='id',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='items_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
