# Generated by Django 5.2.8 on 2025-11-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_remove_orderitem_id_orderitem_items_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='items_id',
            new_name='item_id',
        ),
    ]
