# Generated by Django 5.2.8 on 2025-11-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_rename_items_id_orderitem_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('returned', 'Returned'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('on_hold', 'On Hold'), ('partially_refunded', 'Partially Refunded'), ('partially_shipped', 'Partially Shipped')], default='pending'),
        ),
    ]
