# Generated by Django 5.2.8 on 2025-11-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=20, null=True, unique=True)),
                ('phone', models.CharField(null=True, unique=True)),
                ('password', models.CharField(max_length=35)),
                ('role', models.CharField(choices=[('vendor', 'Vendor'), ('customer', 'Customer')], max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
