# Generated by Django 5.2.8 on 2025-11-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
