# Generated by Django 5.2.8 on 2025-11-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_account_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='role',
            new_name='user_type',
        ),
    ]
