# Generated by Django 5.2.8 on 2025-11-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_account_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_id',
            field=models.IntegerField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
