# Generated by Django 5.2.8 on 2025-11-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_account_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_id',
            field=models.BigIntegerField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
