# Generated by Django 5.2.8 on 2025-11-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_account_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
    ]
