# Generated by Django 5.2.8 on 2025-11-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_account_is_authenticated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
